spring.datasource.url=jdbc:h2:mem:labdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

jwt.secret=sparky-the-horizon-bmth-fan-platform-super-secret-key-2026-cs2031
jwt.expiration=86400000
